version: 2
updates:
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: ""
  directory: /github
  schedule:
    interval: weekly
- package-ecosystem: ""
  directory: /
  schedule:
    interval: weekly
